name = "vibeblocks"
compatibility_date = "2026-02-28"
workers_dev = true
preview_urls = true

[assets]
directory = "./docs/_build/html"

[[routes]]
pattern = "vibeblocks.aadigitalbusiness.com"
custom_domain = true
